service: aws-python

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  timeout: 30
  memorySize: 10240


functions:
  hello:
    handler: handler.decompile_bytecode
    events:
      - http:
          path: /
          method: post